name: FactionEssentials
main: FactionEssentials\Main
version: 1.0.0
api: 5.0.0
author: ApexPELegitz
description: Advanced Faction Essentials for PocketMine API 5

commands:
  sethome:
    description: Set a home
    permission: factionessentials.sethome
  homes:
    description: List your homes
    permission: factionessentials.homes
  home:
    description: Teleport to a home
    permission: factionessentials.home
  seehomes:
    description: View player homes
    permission: factionessentials.seehomes
  seehome:
    description: Teleport to player home
    permission: factionessentials.seehome
  setwarp:
    description: Set a warp
    permission: factionessentials.setwarp
  warp:
    description: Teleport to a warp
    permission: factionessentials.warp
  warps:
    description: List warps
    permission: factionessentials.warps
  back:
    description: Return to last location
    permission: factionessentials.back
  break:
    description: Break bedrock you look at
    permission: factionessentials.break
  tpall:
    description: Teleport all players to you
    permission: factionessentials.tpall
  tpa:
    description: Request teleport to player
    permission: factionessentials.tpa
  tpahere:
    description: Request player teleport to you
    permission: factionessentials.tpa
  tpaccept:
    description: Accept teleport request
    permission: factionessentials.tpa
  tpdeny:
    description: Deny teleport request
    permission: factionessentials.tpa
  top:
    description: Teleport to highest block
    permission: factionessentials.top

permissions:
  factionessentials.*:
    default: op
  factionessentials.sethome:
    default: true
  factionessentials.homes:
    default: true
  factionessentials.home:
    default: true
  factionessentials.setwarp:
    default: op
  factionessentials.warp:
    default: true
  factionessentials.warps:
    default: true
  factionessentials.back:
    default: true
  factionessentials.break:
    default: op
  factionessentials.tpall:
    default: op
  factionessentials.tpa:
    default: true
  factionessentials.top:
    default: true
  factionessentials.seehomes:
    default: op
  factionessentials.seehome:
    default: op
